### ISSUE TITLE
How to backup or restore debs in aptik-gtk ?

### ISSUE THREAD

**Issue by repsorp** [teejee2008/aptik#1]
And also where is the "archives" directory (Installed Software) ?

Aptik-gtk v18.5
Ubuntu 16.04

**Comment by teejee2008** [comment]
In the main window navigation sidebar:
Cache -> Downloaded packages
Packages -> Installed software

Downloaded packages are copied to cache/files/debian in backup path.

Take a look at the [user manual](https://github.com/teejee2008/aptik/blob/master/MANUAL.md)

**Comment by repsorp** [comment]
OK Thanks
But I do I have to move my previous debs (aptik v.17.10 > debs directory ) ?
Couldn't find them anywhere

**Comment by repsorp** [comment]
I couldn't find any of my previously installed software that used to be in the "archives" directory...
None of them are listed in Packages -> Installed software 
Am I missing something ?

**Comment by repsorp** [comment]
No, I'm not trying to restore a backup, just trying to figure it out.

You say that the "archives" directory in previous version contains download packages.
But a lot of my packages contained in this previous "archives" directory are actually missing in  /var/cache/apt/archives...
And when I say a lot I mean a lot... (more than 2000... some being duplicates though)

You also say that the packages that are actually installed are listed in packages/files/selected.list.
But in my case this selected.list file is empty.

And what about debs ?
I used to drop debs on the application as asked by aptik when a missing deb was detected while doing an "Installed software" backup.
Where are they now and how could these debs be restored ?

Sorry If I'm missing something and thanks for your help anyway

**Comment by forsomefun** [comment]
How do I find the old version
Unfortunately I added the program before the switch. Last weekend

**Comment by teejee2008** [comment]
You can place debs in the debs/files folder to install them on restore

**Comment by teejee2008** [comment]
Previous version: https://github.com/teejee2008/aptik-legacy

Download are available on the Releases page

**Comment by repsorp** [comment]
The only way to backup debs with Aptik 18.5 is to move the debs to the debs/files folder ?
No drag and drop option as in previous version  ?

**Comment by teejee2008** [comment]
Fixed in v18.5.1. You can drag drop deb files on main window.
