### ISSUE TITLE
Cannot restore from backup

### ISSUE THREAD

**Issue by tspeidel** [teejee2008/aptik#14]
I am unable to restore items from a backup. Suppose I'm trying to restore only themes. My backup directory looks as follows:

```
/media/tspeidel/Data/Backup/Ubuntu_Aptik_March_2018/themes
├── Adapta-Eta.tar.gz
├── Adapta-Nokto-Eta.tar.gz
├── Adapta-Nokto.tar.gz
├── Adapta.tar.gz
├── Adwaita-dark.tar.gz
├── Adwaita.tar.gz
├── Ambiance.tar.gz
├── Arc-Darker.tar.gz
├── Arc-Dark.tar.gz
├── Arc.tar.gz
├── Numix Daily.tar.gz
├── Radiance.tar.gz
└── Raleigh.tar.gz

```

When I try to restore in Aptik GTK v18.5.2, I select **Themes** only, click **Restore All Items**, Aptik complains it cannot find the directory:
![image](https://user-images.githubusercontent.com/6731198/39957572-7cc45766-55b2-11e8-8ff3-ae2b2867c333.png)

**Comment by teejee2008** [comment]
These backups seems to have been created with previous version of Aptik. Use the previous version to restore it.

You can try moving the files to themes/files folder.
