### ISSUE TITLE
No Aptik-GTK for 14.04

### ISSUE THREAD

**Issue by kintnerrr** [teejee2008/aptik#15]
Hi there,

I'm on Linux Mint 17.3.  There is a version of Aptik for 14.04 in the repo, but not Aptik-GTK.  I can't install the 16.04 version of the GTK frontend and can't resolve the dependencies.  Could we get a build of Aptik-GTK for 14.04 added to the PPA pretty please?  If not, what version of Aptik do I need to roll back to in order to regain the UI?  Ironically, Aptik did not back up its own .deb, so I don't have an archive from the last working version available.  

Thank you!

**Comment by teejee2008** [comment]
The new version of Aptik GTK is built on newer version of GTK toolkit. Ubuntu 14.04 has an older version of GTK in its repos.

Download an older version of Aptik from following page:
https://github.com/teejee2008/aptik-legacy/releases

Try v17.10. If it doesn't work then try an older version.

**Comment by xSeekTruthx** [comment]
I just took a ride on the 14.04 roller coaster. Installed 18, installed gtk, removed 18, removed gtk, installed 17.10, removed 17.10, installed 17.4.... Just want to update notes that there is a specific deb for 14.04 being 17.4 - download, double click and install.
