### ISSUE TITLE
Trouble Restoring Home Folder ?

### ISSUE THREAD

**Issue by SarahSzabo** [teejee2008/aptik#18]
I'm having an issue restoring my home folder. More here: https://askubuntu.com/questions/1040994/restoring-aptik-data

For whatever reason, I can't find the Pictures or Music Folder in the temp archive either. I don't think it recorded it for some reason.

**Comment by teejee2008** [comment]
The temp archive is a temporary file. It looks like the backup didn't complete successfully, or it was cancelled while it was in progress.

**Comment by SarahSzabo** [comment]
Darn, I'm just happy that my music library was saved. I had it on another hard disk anyway.
