### ISSUE TITLE
Exclude dropbox-folders from backup

### ISSUE THREAD

**Issue by gertjanscholten** [teejee2008/aptik#19]
Hi,
Using aptik for the first time, so maybe I'm overlooking something :)

When I run the program for a backup of the home-folder, a backup of dropbox (temporary) folders is also included:
- /home/<username>/Dropbox/.dropbox.cache
- /home/gertjanscholten/.dropbox
- /home/gertjanscholten/.dropbox-dist

The latter is logic to include as it is the dropbox client. However, the first seems to create an infinite loop as it tries to copy a folder which is updated as dropbox syncs. The second contains the local dropbox database which is recreated in case of a new installation.

Would it be possible to add the first to to a default exclusion list?

Cheers, Gertjan

**Comment by teejee2008** [comment]
I'll check this and let you know. You can exclude files if you use Aptik from command line using the `--exclude-from` option. The GUI doesn't have an option to exclude files. I'll add an option to the GUI in a future version.

**Comment by 2635599** [comment]
teejee this is a much better responce from you than the last thread i commented in. thanks

can you provide a link for using aptik via terminal? thanks

**Comment by yochananmarqos** [comment]
@2635599 From the README under [Usage](https://github.com/teejee2008/aptik#usage):

> Available commands and options are documented in the [User Manual](https://github.com/teejee2008/aptik/blob/master/MANUAL.md)

**Comment by teejee2008** [comment]
The free version of Aptik is no longer maintained

A paid version is available with more features.

https://teejeetech.in/2019/07/14/aptik-v19-07/
