### ISSUE TITLE
Deleting Mount Entries

### ISSUE THREAD

**Issue by MarkP2015** [teejee2008/aptik#2]
Assuming using a USB flash/thumb drive as the APTIK install for all it does, in what location will I find <basepath>/mounts to delete crypttab? Copy of User Manual below. I'm a computer illiterate (obvs).

Mount Entries
Backup
Usage: aptik --backup-mounts
Following actions are executed for backup:

    Entries in /etc/fstab and /etc/crypttab are saved to backup folder <basepath>/mounts . Entries are saved individually as <mount-point>.fstab and <dev-name>.crypttab. You can delete files for any mount entries that you do not wish to restore.

**Comment by teejee2008** [comment]
<basepath> is the location you have selected for backup. For example, if you selected /data/usbdrive then you will find the crypttab entries under /data/usbdrive/mounts/files/.

**Comment by teejee2008** [comment]
If you are using aptik from command line, then your current directory is the basepath. 
Else you can specify with --basepath option
`sudo aptik --backup-mounts --basepath /mnt/usbdrive/`
