### ISSUE TITLE
backup update and restore repository ppa Linux Mint 18.3 to 19

### ISSUE THREAD

**Issue by candrapersada** [teejee2008/aptik#20]
how to backup, update, and restore, repository ppa for update Linux Mint 18.3 to Linux Mint 19?

**Comment by teejee2008** [comment]
Run "aptik --backup-repos" to backup and "aptik --restore-repos" to restore PPA on new system.

If you are using GUI then selected click "Backup Mode"="Backup" and "UI Mode"="Advanced". Open the "Repos" tab from sidebar and click "backup" button.

**Comment by candrapersada** [comment]
aptik-gtk add to official linux mint repository

**Comment by teejee2008** [comment]
Please make a request for this with the Linux Mint team
