### ISSUE TITLE
UI problems

### ISSUE THREAD

**Issue by CottonEaster** [teejee2008/aptik#22]
1) One looks in vain for a 'go' or 'backup' option, until one realises one must click 'backup' in the left pane.

More serious, perhaps, is 

2) In the 'backup' window/pane/thing, one heading is called 'select items'. 'Select items' has the grammatical form of an imperative; am I being asked to selected some items? Or is what is meant 'selected items'? And, either way, how do 'settings' - 'settings' being the title of the left column - come in? Also - and let's give this its own number -

3) how do the 'icons' mentioned in the left column relate to the 'icon packages' mentioned in the right column?

Perhaps English is not your first language, but these textual problems do make it hard to understand how to use your tool.

Also, 4) it would be helpful were the words 'include' and 'exclude' to be italicised (on the 'backup' page, I mean).

Also, 5) is it by design that the program switches to terminal mode when I run the backup? Perhaps a general problem - one that conributes to other, more specific problems - is that the exact function of the leftmost column - the one that says 'General / Backup / Terminal' - is unclear. Are those options different stages one must go through? Or are they pages of settings? Something else?

EDIT: 6) I cannot determine how to exclude the cache from the backup.

**Comment by teejee2008** [comment]
Yes, the sidebar items are "pages" that the user must go through. Will it be more clear if I add Previous/Next buttons below each page?

**Comment by CottonEaster** [comment]
> Will it be more clear if I add Previous/Next buttons below each page?

Yes, _if_ (and only if) the user must indeed go through each of those pages. But does the user actually need to through each of them? The user need not go through 'the terminal' page, for one thing. I think it would be better to give some sort of informative title to the leftmost column. It is hard for me to advise, though, since I do not really understand what each column does.

**Comment by teejee2008** [comment]
User can choose which pages to go through. If I only want to backup themes and icons (for example) I'll only go to those pages and click the Backup button at the bottom. I don't this it is confusing.

The terminal shows the progress after clicking the Backup/Restore button. It shows the output of the **aptik** command. It required for seeing the progress of some items such as "Home" which requires a few minutes to complete.
