### ISSUE TITLE
How to save the terminal output ? [Ubuntu 18.10]

### ISSUE THREAD

**Issue by repsorp** [teejee2008/aptik#27]
Hi,

Is there any way to save the terminal output at the end of the restore process ?
'Command | tee' doesn't work here and copy/paste not available

Thanks in advance

Aptik-gtk v.18.8
Ubuntu 18.10

**Comment by teejee2008** [comment]
The free version of Aptik is no longer maintained

A paid version is available with more features.
https://teejeetech.in/2019/07/14/aptik-v19-07/
