### ISSUE TITLE
packages-list empty

### ISSUE THREAD

**Issue by abstinent** [teejee2008/aptik#3]
I use Linux Mint Cinnamon 18.3.

Command aptik  --list-installed-user results in 0 packages. Impossible.
Even in installed.list there are no user-packages.

**Comment by repsorp** [comment]
Same here
Ubuntu 16.04

![capture du 2018-05-03 12-36-32](https://user-images.githubusercontent.com/6297032/39572256-bf0aae9e-4ece-11e8-8dc3-20394c55e974.png)

**Comment by teejee2008** [comment]
is aptitude installed? type `aptitude --version`

**Comment by repsorp** [comment]
~$ aptitude --version
aptitude 0.7.4 compiled at Dec  9 2015 19:30:45
Compiler: g++ 5.3.1 20151207
Compiled against:
  apt version 5.0.0
  NCurses version 6.0
  libsigc++ version: 2.6.2
  Gtk+ support disabled.
  Qt support disabled.

Current library versions:
  NCurses version: ncurses 6.0.20160213
  cwidget version: 0.5.17
  Apt version: 5.0.0

**Comment by teejee2008** [comment]
run this; `aptitude search --disable-columns -F '%p|%v|%C|%M|%d' '?true' | grep installed`

it will print out the status of installed packages

**Comment by abstinent** [comment]
No, this isn't the list of my installed repository packages.

autopkgtest|<keine>|vollständig gelöscht||automatic as-installed testing for Debian packages
binstats|<keine>|vollständig gelöscht||Statistics tool for installed programs
casper|1.376.2|Installiert||Run a "live" preinstalled system from read-only media
casper:i386|<keine>|vollständig gelöscht||Run a "live" preinstalled system from read-only media
clutter-1.0-tests|<keine>|vollständig gelöscht||Open GL based interactive canvas library (installed test programs)
clutter-1.0-tests:i386|<keine>|vollständig gelöscht||Open GL based interactive canvas library (installed test programs)
debsums|<keine>|vollständig gelöscht||tool for verification of installed package files against MD5 checksums
dirtbike|<keine>|vollständig gelöscht||turn system-installed Python packages into wheels
glib-networking-tests|<keine>|vollständig gelöscht||network-related giomodules for GLib - installed tests
glib-networking-tests:i386|<keine>|vollständig gelöscht||network-related giomodules for GLib - installed tests
gnome-desktop-testing|<keine>|vollständig gelöscht||runner for GNOME installed tests
gnome-desktop-testing:i386|<keine>|vollständig gelöscht||runner for GNOME installed tests
heat-cfntools|<keine>|vollständig gelöscht||Tools required to be installed on Heat provisioned cloud
ideviceinstaller|1.1.0-0ubuntu2|Installiert||Utility to manage installed applications on an iDevice
ideviceinstaller:i386|<keine>|vollständig gelöscht||Utility to manage installed applications on an iDevice
ideviceinstaller-dbg|<keine>|vollständig gelöscht||Utility to manage installed applications on an iDevice - debug
ideviceinstaller-dbg:i386|<keine>|vollständig gelöscht||Utility to manage installed applications on an iDevice - debug
install-info|6.1.0.dfsg.1-5|Installiert||Manage installed documentation in info format
install-info:i386|<keine>|vollständig gelöscht||Manage installed documentation in info format
jasper|<keine>|vollständig gelöscht||Configure a preinstalled ext2/3 system image
kde-sc-dev-latest|<keine>|vollständig gelöscht||ensure that the latest KDE Development Platform 4 is installed
launchy|<keine>|vollständig gelöscht||smart search launcher for installed programs or files
launchy:i386|<keine>|vollständig gelöscht||smart search launcher for installed programs or files
libapp-info-perl|<keine>|vollständig gelöscht||module to provide metadata about software packages installed
libc6-armel-armhf-cross|<keine>|vollständig gelöscht||Dummy package to get libc6:armel installed
libc6-armhf-armel-cross|<keine>|vollständig gelöscht||Dummy package to get libc6:armhf installed
libc6-dev-armel-armhf-cross|<keine>|vollständig gelöscht||Dummy package to get libc6-dev:armel installed
libc6-dev-armhf-armel-cross|<keine>|vollständig gelöscht||Dummy package to get libc6-dev:armhf installed
libglib2.0-tests|<keine>|vollständig gelöscht||GLib library of C routines - installed tests
libglib2.0-tests:i386|<keine>|vollständig gelöscht||GLib library of C routines - installed tests
libmodule-find-perl|<keine>|vollständig gelöscht||module to find and use installed Perl modules
libmodule-path-perl|<keine>|vollständig gelöscht||module to get the full path to a locally installed Perl module
mint-meta-cinnamon|<keine>|vollständig gelöscht||Set of packages installed by default in the Cinnamon edition of Linux Mint
mint-meta-kde|<keine>|vollständig gelöscht||Set of packages installed by default in the KDE edition of Linux Mint
mint-meta-mate|<keine>|vollständig gelöscht||Set of packages installed by default in the MATE edition of Linux Mint
mint-meta-xfce|<keine>|vollständig gelöscht||Set of packages installed by default in the Xfce edition of Linux Mint
pango1.0-tests|<keine>|vollständig gelöscht||Layout and rendering of internationalized text - installed tests
pango1.0-tests:i386|<keine>|vollständig gelöscht||Layout and rendering of internationalized text - installed tests
pmuninstall|<keine>|vollständig gelöscht||script to uninstall modules installed from CPAN
timeshift-btrfs|<keine>|vollständig gelöscht||System restore utility for Linux systems installed on BTRFS partitions
timeshift-btrfs:i386|<keine>|vollständig gelöscht||System restore utility for Linux systems installed on BTRFS partitions

**Comment by teejee2008** [comment]
Please install the attached package and let me know if it fixes the issue.

[aptik-v18.5.1-amd64.zip](https://github.com/teejee2008/aptik/files/1972043/aptik-v18.5.1-amd64.zip)

**Comment by teejee2008** [comment]
Yes, issue is on systems with non-english locales. Please try the build attached in previous post and let me know if it fixes the issue.

**Comment by repsorp** [comment]
![capture du 2018-05-03 19-57-05](https://user-images.githubusercontent.com/6297032/39594178-30ff526a-4f0c-11e8-9270-d150c4446636.png)

**Comment by teejee2008** [comment]
Sorry, forgot to update the version. Try this one:

[aptik-v18.5.1-test2-amd64.zip](https://github.com/teejee2008/aptik/files/1972085/aptik-v18.5.1-test2-amd64.zip)

**Comment by repsorp** [comment]
My packages are back... 
![capture du 2018-05-03 20-08-48](https://user-images.githubusercontent.com/6297032/39594734-d4ed7978-4f0d-11e8-86c9-7b7688d526ae.png)

**Comment by teejee2008** [comment]
Great! Thanks for your help.

**Comment by repsorp** [comment]
Thanks for your reactivity
Keep up the good work

**Comment by abstinent** [comment]
With test2 everything is okay- thank you.
