### ISSUE TITLE
Home Folder archive file far too large

### ISSUE THREAD

**Issue by gozo97** [teejee2008/aptik#32]
Hello. I am attempting to backup my installation of Mint 18.3 Cinnamon using Aptik-GTK with the one-click option. All the backup seems to be successful apart from my home/ folder. The home partition is about 74 GB but Aptik tries to archive it to a much larger file and finally halts due to lack of disk space. The same thing happens if I try an individual backup of the home folder rather than the one-click choice, it simply runs out of space.
I have attached a copy of the terminal output which shows the archived file to be 245 GB! 
Any suggestions very welcome, thank you.

[Terminal.txt](https://github.com/teejee2008/aptik/files/3029275/Terminal.txt)

**Comment by teejee2008** [comment]
The free version of Aptik is no longer maintained

A paid version is available with more features.
https://teejeetech.in/2019/07/14/aptik-v19-07/
