### ISSUE TITLE
Backup of config files in /etc and manually compiled apps

### ISSUE THREAD

**Issue by jbrepogmailcom** [teejee2008/aptik#34]
Hello! Many apps have config files somewhere deep within /etc directory (like snapper). Are such config files backed up as well?

How are backed applications, that are downloaded from github to /home/user directory and then manually compiled?

Thanks for answer, Jan

**Comment by teejee2008** [comment]
The free version of Aptik is no longer maintained

A paid version is available with more features.

https://teejeetech.in/2019/07/14/aptik-v19-07/
