### ISSUE TITLE
Want to exclude a folder when backing up home

### ISSUE THREAD

**Issue by 2635599** [teejee2008/aptik#35]
i would like to know if these is anyway to exclude a folder from being backed up when i backup home? i have plex media server installed and with it home takes forever to backup, not to mention it makes the backup massive. i would like to exclude it during the back up. thanks

KDE Neon 64 Bit: Kernel 5.1.0
AMD FX 6300, Asus 970 Gaming/Aura, Samsung 120 Gig 850 EVO, 16Gig DDR3, 
USB 3 Card, AOC 29" Ultra Wide 2560x1080. nVidia 750Ti(430 Driver),
SATA 1TB, 750 & 500Gig Drives, USB 3 2TB & 1.5TB Drives

**Comment by 2635599** [comment]
no comment one way or the other yet?

**Comment by rasmith1959** [comment]
At the moment there's no way this can be done using the graphic user interface, but can easily be done from the command line. You can do this by using the option --exclude-from [text file of Directories and/or files to exclude]. Here's an example of how I use it:

sudo aptik --backup-all --basepath /media/roy/'Linux Backups'/Aptik --scripted --exclude-from .skipped_files

Aptik will read the text file and skip those files in your home folder when the --exclude-from [text file] is used. In my example above it reads the .skipped_files file which contains:

Music
Pictures
Dropbox
.Dropbox

Now when I use aptik and use the option --exclude-from .skipped_files it will skip over those folders in my Home directory and the archive it creates is much smaller that if I hadn't used it.

**Comment by teejee2008** [comment]
The free version of Aptik is no longer maintained

A paid version is available with more features.

https://teejeetech.in/2019/07/14/aptik-v19-07/
