### ISSUE TITLE
Unable to locate package aptik for Xubuntu 19.04

### ISSUE THREAD

**Issue by tuxthepenguin84** [teejee2008/aptik#36]
**Describe the bug**
When adding the PPA for Ubuntu/Xubuntu it adds the distrubution as "disco". I don't think the repo supports disco so it won't install aptik or aptik-gtk.

**To Reproduce**
sudo add-apt-repository -y ppa:teejee2008/ppa
sudo apt-get update
sudo apt-get install aptik aptik-gtk

It will then say aptik & aptik-gtk could not be located

**System:**
 - Linux Distribution Name and Version: Xubuntu 19.04
 - XFCE

**Workaround:**
Modify the first line of /etc/apt/sources.list.d/teejee2008-ppa-disco.list
And replace disco with cosmic for the distribution
sudo apt update
sudo apt install aptik aptik-gtk
Everything should install fine now.

**Comment by teejee2008** [comment]
The free version of Aptik is no longer maintained

A paid version is available with more features.

https://teejeetech.in/2019/07/14/aptik-v19-07/
