### ISSUE TITLE
RC Clone

### ISSUE THREAD

**Issue by MarkP2015** [teejee2008/aptik#5]
THIS IS NOT AN ISSUE, AS GITHUB SUGGESTS ABOUT ALL POSTS. Aptik restored a number of user installed apps today. One is RClone. It xfers/syncs files between this computer and a cloud storage account. When I tried to restore /Desktop via RClone, which has previously had /Desktop sent to it as storage in the cloud, RClone balked and wants a it's config and other info back. If Aptik took it, it didn't restore it.  I get confused. I don't know what Aptik does or doesn't do.

**Comment by teejee2008** [comment]
rclone keeps its configs in your home folder, so if you backed up your home directory data with Aptik then it should be restored.

Check for a `.rclone` folder in home or under .config/rclone (show all hidden files in file manager)
