### ISSUE TITLE
Latest version is not opening gui with 18.04, only command line works

### ISSUE THREAD

**Issue by AntiNSA** [teejee2008/aptik#6]
HI, I have tried purging, reinstall, etc. I can not get the Gui to lanch, there is no Aptik shortcut either...

**Comment by teejee2008** [comment]
Install the aptik-gtk package

**Comment by AntiNSA** [comment]
Thanks! A wonderful program. Thanks for all your hard work.

**Comment by HuShifang** [comment]
Had the same issue in Kubuntu 18.04, but installing and running `aptik-gtk` similarly resolved it. Thanks for the clarification, and all the great work on the app!

**Comment by azigit** [comment]
Same problem: on Linux Mint 17.3 I installed aptik version 18.6 from the ppa. There's no gui and the aptik-gtk package does not seem to be available. apt-cache search returns aptik and aptik-battery-monitor only.
Thanks.

**Comment by zcot** [comment]
@azigit aptik-gtk is a different software, in repository: https://github.com/teejee2008/aptik-gtk
