### ISSUE TITLE
Application launcher disappeared in Ubuntu 16.04

### ISSUE THREAD

**Issue by arderyp** [teejee2008/aptik#8]
I've been using Aptik for the past 2 years on Ubuntu 16, running it monthly.  All of a sudden, the application launcher registry disappeared... that is, I am no longer able to search for 'Aptik' in the Unity launcher and find/launch the app.  I do still have the command line option, so the software is still installed.  I tried removing it and reinstalling it with apt, but still no luck.  I am not sure what system backup broke this.  I keep Ubuntu up to date, and I did notice an Aptik update within the last month, but didn't try running the application immediately after that.

This seems to have affected all of the various machines on which I have Aptik installed (all running Ubuntu 16.04).  I just now noticed that the Application launcher is not available on any of them.

Is there any suggestion for how to go about launching the GUI from the  command line, or resolving this issue otherwise?

**Comment by arderyp** [comment]
nevermind, looks like a resolution in another issue resolves this: https://github.com/teejee2008/aptik/issues/6

```
$ sudo apt install aptik-gtk
...
$ atik-gtk
```

**Comment by teejee2008** [comment]
The **Backup** button on **General** tab is for selecting the mode. Use the others tabs - All Items, Repos, Packages,...etc - for creating backups

**Comment by arderyp** [comment]
@teejee2008, thanks for the inso.  Does this mean the old "One Click Backup" options has been removed?  If so, is there a reason?  It was mighty convenient...

**Comment by arderyp** [comment]
nevermind, I see the "backup all item" option now, thanks!
